#!/bin/bash
#
# rss-shortener
#
# chkconfig: 2345 84 16
# description: Start up the RSS Shortener server.

# Source function library
. /etc/init.d/functions

RETVAL=$?
PID_FILE="/var/applications/pid/rss_shortener.pid"
RSS_SHORTENER="/var/applications/rss-shortener"

case "$1" in
  status)
	RESULT=`curl -s http://localhost:8888/_/status`
	if [ "$RESULT" = 'ok' ];
	  then
	    echo "OK"
	    exit 0
	  else
	    echo "Not OK"
	    exit 1
	fi
	;;	
  start)
	if [ -f $RSS_SHORTENER/server.py ];
	  then
	    echo -n "Starting Tornado: "
	    daemon $"daemonize -u tornado -p $PID_FILE $RSS_SHORTENER/server.py"
	    echo
	fi
	;;
  stop)
	echo -n $"Stopping Tornado"
	killproc -p $PID_FILE python
	echo
	;;
  *)
	echo $"Usage: $0 {start|stop}"
	exit 1
	;;
esac

exit $RETVAL

